### PR TITLE
[WIP] ci: Setup CI based on tekton

### PR DESCRIPTION
**Pull request by mbharatk**
### What does this PR do?
Part of [redhat-appstudio/infra-deployments #130
](https://github.com/redhat-appstudio/infra-deployments/pull/130)

### CODE REVIEW

**Comment by mbharatk** [comment]
@sparkoo PTAL

**Comment by mbharatk** [comment]
@sparkoo I see that two checks are failing, one of them is golang lint which I'm guessing is not required for this PR. The other check (Semantic Pull Request) is what I'm not sure about and I wanted to check with you what it is, could you please provide me some context on it?

**Comment by sparkoo** [comment]
@mbharatk https://github.com/zeke/semantic-pull-requests you just need to prefix your PR title. In this case `ci:` would fit the best.

**Comment by mbharatk** [comment]
@sparkoo Thank you. I have updated the title, could you please review the PR. There are no more commits pending from my end.

**Comment by sparkoo** [comment]
@mbharatk can you please merge latest main? I've just committed update to go 1.17 and I see you're using ubi8/go-toolset, which I think is only 1.16.

Also what does it exactly do? Does it build, test and build image from PR branch and push image somewhere? Does it write some comment to PR or add check or something?

**Comment by mbharatk** [comment]
> Also what does it exactly do? Does it build, test and build image from PR branch and push image somewhere? Does it write some comment to PR or add check or something?

This will enable App Studio Github Repos to easily configure Tekton as their CI for PR checks.
The goal of Pipelines as Code is to let you define your Tekton templates inside your source code repository and have the pipeline run and report the status of the execution when triggered by a Pull Request or a Push.


> can you please merge latest main? I've just committed update to go 1.17 and I see you're using ubi8/go-toolset, which I think is only 1.16.

@sparkoo Sure, I can pull the latest main and try with that.

**Comment by sparkoo** [comment]
@mbharatk any update ?

**Pull request closed without merging**
